// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChW86DkL_buZnK25P1-JkNg1QBRhcoy2g',
    appId: '1:216330589426:web:dbb4bbd390f498b9d5ac6b',
    messagingSenderId: '216330589426',
    projectId: 'safariapp-5965d',
    authDomain: 'safariapp-5965d.firebaseapp.com',
    storageBucket: 'safariapp-5965d.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChW86DkL_buZnK25P1-JkNg1QBRhcoy2g',
    appId: '1:216330589426:android:dbb4bbd390f498b9d5ac6b',
    messagingSenderId: '216330589426',
    projectId: 'safariapp-5965d',
    authDomain: 'safariapp-5965d.firebaseapp.com',
    storageBucket: 'safariapp-5965d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChW86DkL_buZnK25P1-JkNg1QBRhcoy2g',
    appId: '1:216330589426:ios:dbb4bbd390f498b9d5ac6b',
    messagingSenderId: '216330589426',
    projectId: 'safariapp-5965d',
    authDomain: 'safariapp-5965d.firebaseapp.com',
    storageBucket: 'safariapp-5965d.firebasestorage.app',
    iosBundleId: 'com.SafariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChW86DkL_buZnK25P1-JkNg1QBRhcoy2g',
    appId: '1:216330589426:ios:dbb4bbd390f498b9d5ac6b',
    messagingSenderId: '216330589426',
    projectId: 'safariapp-5965d',
    authDomain: 'safariapp-5965d.firebaseapp.com',
    storageBucket: 'safariapp-5965d.firebasestorage.app',
    iosBundleId: 'com.SafariApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChW86DkL_buZnK25P1-JkNg1QBRhcoy2g',
    appId: '1:216330589426:web:dbb4bbd390f498b9d5ac6b',
    messagingSenderId: '216330589426',
    projectId: 'safariapp-5965d',
    authDomain: 'safariapp-5965d.firebaseapp.com',
    storageBucket: 'safariapp-5965d.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}